package com.francis.byteworkstest.enumType;

public enum FoodType {
	
	RICE_AND_STEW, RICE_AND_PEPPERSOUP,  FRIED_RICE,  JELLOF_RICE,  RICE_AND_BEANS,
	
	GARRI_AND_VEGETABLESOUP,  GARRI_AND_EGGUSUSOUP,  GARRI_AND_OKROSOUP, PEPPER_RICE


}
